package io.github.texport.superkassa.jvm.shared.strings.api.key

import io.github.texport.superkassa.jvm.shared.strings.api.ErrorKey

/**
 * Перечисление (enum), определяющее ключи ошибок для валидации настроек.
 * Разрешается в трехъязычные локализованные сообщения через [io.github.texport.superkassa.jvm.shared.strings.api.ErrorResolver].
 *
 * Потокобезопасность: Перечисления (enums) являются потокобезопасными по своей природе.
 */
enum class SettingsErrorKey(override val code: String) : ErrorKey {
    SQLITE_NOT_ALLOWED("SETTINGS_SQLITE_NOT_ALLOWED"),
    SERVER_MODE_ONLY("SETTINGS_SERVER_MODE_ONLY"),
    OFD_PROTOCOL_VERSION("SETTINGS_OFD_PROTOCOL_VERSION"),
    OFD_TIMEOUT("SETTINGS_OFD_TIMEOUT"),
    OFD_RECONNECT_INTERVAL("SETTINGS_OFD_RECONNECT_INTERVAL"),
    STORAGE_ENGINE_BLANK("SETTINGS_STORAGE_ENGINE_BLANK"),
    STORAGE_ENGINE_INVALID("SETTINGS_STORAGE_ENGINE_INVALID"),
    JDBC_URL_BLANK("SETTINGS_JDBC_URL_BLANK"),
    JDBC_URL_INVALID_SCHEME("SETTINGS_JDBC_URL_INVALID_SCHEME"),
    NODE_ID_BLANK("SETTINGS_NODE_ID_BLANK"),
    DATABASE_USER_BLANK("SETTINGS_DATABASE_USER_BLANK"),
    DATABASE_PASSWORD_BLANK("SETTINGS_DATABASE_PASSWORD_BLANK"),
    OFD_PROVIDER_KEY_BLANK("SETTINGS_OFD_PROVIDER_KEY_BLANK"),
    CHANNEL_NAME_BLANK("SETTINGS_CHANNEL_NAME_BLANK"),
    UNKNOWN_DELIVERY_CHANNEL("SETTINGS_UNKNOWN_DELIVERY_CHANNEL"),
    PAYLOAD_TYPE_BLANK("SETTINGS_PAYLOAD_TYPE_BLANK"),
    DOCUMENT_FORMAT_BLANK("SETTINGS_DOCUMENT_FORMAT_BLANK"),
    DESTINATION_BLANK("SETTINGS_DESTINATION_BLANK"),
    EMAIL_DESTINATION_INVALID("SETTINGS_EMAIL_DESTINATION_INVALID"),
    PHONE_DESTINATION_INVALID("SETTINGS_PHONE_DESTINATION_INVALID"),
    TELEGRAM_DESTINATION_INVALID("SETTINGS_TELEGRAM_DESTINATION_INVALID"),
    PRINT_CONFIG_MISSING("SETTINGS_PRINT_CONFIG_MISSING"),
    PRINT_PAPER_WIDTH_INVALID("SETTINGS_PRINT_PAPER_WIDTH_INVALID"),
    PRINT_HOST_INVALID("SETTINGS_PRINT_HOST_INVALID"),
    PRINT_PORT_INVALID("SETTINGS_PRINT_PORT_INVALID"),
    EMAIL_CONFIG_MISSING("SETTINGS_EMAIL_CONFIG_MISSING"),
    EMAIL_PARAMS_INVALID("SETTINGS_EMAIL_PARAMS_INVALID"),
    SMS_CONFIG_MISSING("SETTINGS_SMS_CONFIG_MISSING"),
    SMS_PROVIDER_URL_INVALID("SETTINGS_SMS_PROVIDER_URL_INVALID"),
    SMS_API_KEY_BLANK("SETTINGS_SMS_API_KEY_BLANK"),
    TELEGRAM_CONFIG_MISSING("SETTINGS_TELEGRAM_CONFIG_MISSING"),
    TELEGRAM_BOT_TOKEN_INVALID("SETTINGS_TELEGRAM_BOT_TOKEN_INVALID"),
    WHATSAPP_CONFIG_MISSING("SETTINGS_WHATSAPP_CONFIG_MISSING"),
    WHATSAPP_ACCESS_TOKEN_BLANK("SETTINGS_WHATSAPP_ACCESS_TOKEN_BLANK"),
    WHATSAPP_PHONE_ID_INVALID("SETTINGS_WHATSAPP_PHONE_ID_INVALID"),
    SETTINGS_FROZEN_SERVER_MODE("SETTINGS_SETTINGS_FROZEN_SERVER_MODE"),
    SETTINGS_FROZEN_DISALLOWED("SETTINGS_SETTINGS_FROZEN_DISALLOWED")
}
